import "./globals.css";
import StoreProvider, { Context } from "../components/state/store-provider";
import Layout from "../components/layout/layout";
import { GetHeaders} from "../library/session-hub";
import { Geist, Geist_Mono } from "next/font/google";
import { SocketProvider } from "@/components/state/socket.provider";
import { AUser } from "@/actions/a.user";
import GlobalMemo from "@/library/chache";

import { IonApp } from "@ionic/react";
import { useContext } from "react";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "Client APP",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let lib = { user: null, token: null, language: null, error: null };
  const { state: { user } } = useContext(Context);
  lib.token = user?.token;

  if (lib.token) {
    try {
      const MemoData = GlobalMemo.memoize(async () => await AUser.IsAuth(lib.token), "auth", 5 * 60 * 1000);
      const { success, message, error, data } = await MemoData();

      if (success) {
        lib.user = { ...data, token: lib.token, language: lib.language };
      } else {
        GlobalMemo.clear("auth");
        lib.error = error || message || "Authentication failed";
      }
    } catch (authError) {
      GlobalMemo.clear("auth");
      lib.error = authError?.message || "Failed to authenticate user";
    }
  }

  if (lib.error) {
    const h = GetHeaders();
    lib.is_auth_error = true;
    GlobalMemo.clear("auth");

    if (h?.referer) {
      await fetch(`${h.referer}api/logout`);
    }
  }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>

        <IonApp>

          <StoreProvider
            error={lib.error || null}
            user={lib.user || {}}
            token={lib.token}
          >
            <SocketProvider lib={lib}>
              <Layout lib={lib}>
                {children}
              </Layout>
            </SocketProvider>
          </StoreProvider>

        </IonApp>

      </body>
    </html>
  );
}